config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'application#index'
    resources :users
    resources :categories, except: [:show]
    resources :surveys, except: [:show]
    resources :polls, except: [:show]
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :votes, only: [:create]
  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :profiles, path: 'my-profile', except: :show
  resources :rewards, path: 'my-rewards', only: [:index]
  resources :enrollments
  resources :polls do
    resources :completions, only: [:create]     
  end
  patch 'questions/:id/move', controller: 'polls', action: :move
  root "home#index"
  resources :surveys do
    resources :completions, only: [:create]     
    resources :enrollments, only: [:new, :create]
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
	belongs_to :organizer, class_name: "User", foreign_key: "user_id"
	belongs_to :category
	has_many :completions, as: :completion_source
	has_many :enrollments, dependent: :destroy
  has_many :experiences, as: :experience_source
  has_many :rewards_cashes, as: :rewards_cash_source
  has_many :survey_rewards, as: :survey_reward_source	
	validates :survey_name, presence: true, length: {minimum: 5}
	validates :description, :start_date, :end_date, :cpi, :loi, :category, :survey_reward, :rewards_cash, :experience, presence: true

	def enrolled(user)
		self.enrollments.where(user_id: [user.id], survey_id: [self.id].empty?)
	end
end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < Admin::ApplicationController
	before_action :set_survey, only: [:show, :edit, :update, :destroy]  
	before_action :authenticate_user!, except: [:index, :show]


	def index
		@surveys = Survey.order(:id)
	end
	
  def create
    @survey = Survey.new(survey_params)

    authorize @survey, :create?
    @survey.organizer = current_user

    respond_to do |format|
      if @survey.save
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

	def edit
		
	end

	def update
		if @survey.update(survey_params)
			flash[:notice] = "Survey has been updated"
			redirect_to survey_url(@survey)
		else
			flash[:alert] = "Survey has not been updated"
			render "edit"
		end
	end

	def destroy
    	@survey.destroy

	    respond_to do |format|
	      format.html { redirect_to admin_surveys_path, notice: "Survey was successfully destroyed." }
	      format.json { head :no_content }
    end

	end

	private

    def survey_params
      params.require(:survey).permit(:survey_name, 
                                    :description, 
                                    :location,
                                    :start_date,
                                    :end_date,
                                    :cpi,
                                    :loi,
                                    :survey_id,
                                    :category_id,
                                    :experience,
                                    :rewards_cash,
                                    :survey_reward
                                    )
    end

	def set_survey
		@survey = Survey.find(params[:id])
	end
end

app/controllers/surveys_controller.rb
  class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :verify_admin, only: [ :new ]

  def index
    @surveys = Survey.order(created_at: :desc)
    @categories = Category.order(:name)
    @enrollments = Enrollment.all
    authorize @surveys, :index?
    @polls = Poll.all.where.not(status: ['draft', 'closed'] )
    @admin_polls = Poll.all
  end

  def show
    authorize @survey, :show?
    @completed_survey =  current_user.completions.where(completion_source_type: "Survey").find_by(completion_source_id: @survey.id)      
  end

  def new
    @survey = Survey.new

    authorize @survey, :new?
  end

  def edit
    authorize @survey, :edit?
  end

  def update
    authorize @survey, :update?

    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @survey, :destroy?
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
    end
  end

  private
    def set_survey
      @survey = Survey.find(params[:id])

      rescue ActiveRecord::RecordNotFound
      flash.alert = "The page you requested does not exist"
      redirect_to surveys_path

    end

    def verify_admin
      unless current_user.admin?
        redirect_to surveys_path
      end
    end

    def survey_params
      params.require(:survey).permit(:survey_name, 
                                    :description, 
                                    :location,
                                    :start_date,
                                    :end_date,
                                    :cpi,
                                    :loi,
                                    :survey_id,
                                    :category_id,
                                    :experience,
                                    :rewards_cash,
                                    :survey_reward
                                    )
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/admin/surveys/_form.html.haml
.mt-8.sm:mx-auto.sm:w-full.sm:max-w-md
  .bg-white.py-8.px-4.shadow.sm:rounded-lg.sm:px-10
    = simple_form_for([:admin, @survey]) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
      .my-2
        = f.input :survey_name, required: true, class: 'block text-sm font-medium text-gray-700'
        .mt-1
        = f.input :description, required: true, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" 
      .my-2
        = f.input :start_date, required: true, class: 'block text-sm font-medium text-gray-700'
      .my-2
        = f.input :end_date, required: true, class: 'block text-sm font-medium text-gray-700'
      .my-2
        = f.input :category_id, required: true, collection: Category.all, label: "Select Category", prompt: true, class: 'block text-sm font-medium text-gray-700'
      .my-2
        = f.input :cpi, input_html: { min: '0', step: 'any'}, required: true, class: 'block text-sm font-medium text-gray-700'
        = f.input :loi, input_html: { min: '0', step: 'any'}, required: true, class: 'block text-sm font-medium text-gray-700'
        = f.input :experience, required: true, class: 'block text-sm font-medium text-gray-700'
        = f.input :rewards_cash, required: true, label: 'CloutCash', class: 'block text-sm font-medium text-gray-700'
      .my-2
        = f.input :survey_reward, required: true, class: 'block text-sm font-medium text-gray-700'

      %p Location
      = f.country_select :location

      %button.w-full.flex.justify-center.mt-4.py-2.px-4.border.border-transparent.rounded-md.shadow-sm.text-sm.font-medium.text-white.bg-blue-600.hover:bg-blue-700.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-blue-500{:type => "submit"}
        = f.button :submit

app/views/admin/surveys/edit.html.haml
= render "admin/application/sidebar"
%body
%header
.min-h-full.flex.flex-col.justify-center.py-12.sm:px-6.lg:px-8
  %h2.mt-6.text-center.text-3xl.font-extrabold.text-gray-900 Edit Survey
  = render "form", survey: @survey
%p{:class => "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto", :type => "button"}= link_to "Back", admin_categories_path

app/views/admin/surveys/index.html.haml
= render "admin/application/sidebar"
.px-4.sm:px-6.lg:px-8
  .sm:flex.sm:items-center
    .sm:flex-auto
      %h1.text-xl.font-semibold.text-gray-900= "Surveys: #{@surveys.count}"
    .mt-4.sm:mt-0.sm:ml-16.sm:flex-none
    - admins_only do
      %button{:class => "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto", :type => "button"}= link_to "New survey", new_survey_path
  .mt-8.flex.flex-col
    .-my-2.-mx-4.overflow-x-auto.sm:-mx-6.lg:-mx-8
      .inline-block.min-w-full.py-2.align-middle.md:px-6.lg:px-8
        .overflow-hidden.shadow.ring-1.ring-black.ring-opacity-5.md:rounded-lg
          %table.min-w-full.divide-y.divide-gray-300
            %thead.bg-gray-50
              %tr
                %th.pl-4.pr-3.text-left.text-sm.font-semibold.text-gray-900.sm:pl-6{:class => "py-3.5", :scope => "col"} Survey ID
                %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} Name
                %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} Created
                %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} Survey
                %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} Description
                %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} Location
                %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} Category
                %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} CPI
                %th.px-3.text-left.text-sm.font-semibold.text-gray-900{:class => "py-3.5", :scope => "col"} LOI
            %tbody.divide-y.divide-gray-200.bg-white
            - @surveys.each do |survey|
              %tr
                %td.whitespace-nowrap.py-4.pl-4.pr-3.text-sm.font-medium.text-gray-900= survey.id
                %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500= survey.survey_name
                %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500= time_format(survey.created_at)
                %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500= link_to "Survey", survey_path(survey)
                %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500= survey.description
                %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500= survey.location
                %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500= survey.category.name
                %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500= survey.cpi
                %td.whitespace-nowrap.px-3.py-4.text-sm.text-gray-500= survey.loi

                %td.relative.whitespace-nowrap.py-4.pl-3.pr-4.text-right.text-sm.font-medium.sm:pr-6
                %td.relative.whitespace-nowrap.py-4.pl-3.pr-4.text-right.text-sm.font-medium.sm:pr-6
                  %a.text-indigo-600= link_to "Edit", edit_admin_survey_path(survey), class: "edit" if policy(survey).edit?
                  %a.text-indigo-600= button_to "Delete", survey_path(survey), method: :delete, data: {confirm: "Are you sure?"}, class: "delete" if policy(survey).destroy?                  
%p{:class => "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto", :type => "button"}= link_to "Back to Dashboard", admin_root_path

app/views/admin/surveys/new.html.haml
= render "admin/application/sidebar"
%body
.min-h-full.flex.flex-col.justify-center.py-12.sm:px-6.lg:px-8
  %h2.mt-6.text-center.text-3xl.font-extrabold.text-gray-900
    New Survey
  = render "form", survey: @survey
%p{:class => "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto", :type => "button"}= link_to "Back", admin_categories_path