config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'application#index'
    resources :users
    resources :categories, except: [:show]
    resources :surveys, except: [:show]
    resources :polls, except: [:show]
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :votes, only: [:create]
  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :profiles, path: 'my-profile', except: :show
  resources :rewards, path: 'my-rewards', only: [:index]
  resources :enrollments
  resources :polls do
    resources :completions, only: [:create]     
  end
  patch 'questions/:id/move', controller: 'polls', action: :move
  root "home#index"
  resources :surveys do
    resources :completions, only: [:create]     
    resources :enrollments, only: [:new, :create]
  end
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true, length: {minimum: 5 }
	validates_uniqueness_of :name

	has_many :surveys, dependent: :destroy
end

app/models/completion.rb
class Completion < ApplicationRecord
  belongs_to :user
  belongs_to :completion_source, polymorphic: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord

  enum :status, { inactive: 0, in_process: 10, completed_full: 20, completed_disqualified: 30, terminated: 40 }

  belongs_to :survey
  belongs_to :user

  validates :user, :survey, presence: true

  validates_uniqueness_of :user_id, scope: :survey_id #user can't be enrolled in a survey more than once
  validates_uniqueness_of :survey_id, scope: :user_id #user can't be enrolled in a survey more than once

  def to_s
    user.to_s + survey.to_s
  end


end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  belongs_to :experience_source, polymorphic: true
end

app/models/guest_user.rb
class GuestUser < User
	attr_accessor :name, :first_name, :last_name, :email
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :questions, dependent: :delete_all
  has_many :experiences, as: :experience_source
  has_many :rewards_cashes, as: :rewards_cash_source

  accepts_nested_attributes_for :questions, :reject_if => :all_blank, :allow_destroy => true

  enum status: { draft: 'draft', open: 'open', closed: 'closed' }

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :age, :gender, :ethnicity, :country, presence: true

  def self.select_options_for_gender
    [['Male', 'male'], ['Female','female'], ['Other','other']]
  end
  def self.select_options_for_ethnicity
    [['American Indian', 'american indian'], ['Asian','asian'], ['Black or African American','black or african american'], ['Hispanic or Latino ', 'hispanic or latino'], ['Native Hawaiian','native hawaiian'], ['White or Caucasian','white or caucasian']]
  end
end

app/models/question.rb
class Question < ApplicationRecord
  acts_as_list
  
  has_many :vote_options, dependent: :delete_all
  belongs_to :poll 
  accepts_nested_attributes_for :vote_options, :reject_if => :all_blank, :allow_destroy => true


  def self.select_options_for_type
    [['Single Select', 'single_select'], ['Multi Select','multi_select']]
  end

  def normalized_votes_for(option)
    votes_summary == 0 ? 0 : (option.votes.count.to_f / votes_summary) * 100
  end

  def votes_summary
    vote_options.inject(0) {|summary, option| summary + option.votes.count}
  end

end

app/models/rewards_cash.rb
class RewardsCash < ApplicationRecord
  belongs_to :rewards_cash_source, polymorphic: true
  belongs_to :user
end

app/models/survey.rb
class Survey < ApplicationRecord
	belongs_to :organizer, class_name: "User", foreign_key: "user_id"
	belongs_to :category
	has_many :completions, as: :completion_source
	has_many :enrollments, dependent: :destroy
  has_many :experiences, as: :experience_source
  has_many :rewards_cashes, as: :rewards_cash_source
  has_many :survey_rewards, as: :survey_reward_source	
	validates :survey_name, presence: true, length: {minimum: 5}
	validates :description, :start_date, :end_date, :cpi, :loi, :category, :survey_reward, :rewards_cash, :experience, presence: true

	def enrolled(user)
		self.enrollments.where(user_id: [user.id], survey_id: [self.id].empty?)
	end
end

app/models/survey_reward.rb
class SurveyReward < ApplicationRecord
  belongs_to :survey_reward_source, polymorphic: true
  belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :organized_surveys, class_name: "Survey", dependent: :destroy
  has_many :completions, dependent: :destroy
  has_many :completed_surveys, through: :completions
  has_many :enrollments
  has_many :rewards_cashes, dependent: :destroy
  has_many :experiences, dependent: :destroy
  has_many :survey_rewards, dependent: :destroy
  has_one :profile, dependent: :destroy
  validates :first_name, :last_name, :email, presence: true
  has_many :votes, dependent: :destroy
  has_many :vote_options, through: :votes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def to_s
  "#{username}"
  end
  
  def voted_for?(question)
    Rails.cache.fetch('user_' + id.to_s + '_voted_for_' + question.id.to_s) { vote_options.any? {|v| v.question == question } }
  end

  def full_name
  "#{first_name} #{last_name}"           
  end

  def enroll_survey(survey)
    self.enrollments.create(survey: survey)
  end

  def total_rewards_cash
  rewards_cashes.sum(:rewards_cash_amount)
  end

  def total_experience
  experiences.sum(:experience_amount)
  end

  def total_survey_reward
  survey_rewards.sum(:survey_reward_amount)
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  validates :vote_options, presence: true
  has_and_belongs_to_many :vote_options
end

app/models/vote_option.rb
class VoteOption < ApplicationRecord
  belongs_to :question
  has_and_belongs_to_many :votes
  has_many :users, through: :votes
  validates :title, presence: true
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/polls_helper.rb
module PollsHelper
  def visualize_votes_for(option)
    content_tag :div, class: 'w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700' do
      content_tag :div, class: 'bg-blue-600 h-2.5 rounded-full',
                  style: "width: #{option.question.normalized_votes_for(option)}%" do
        "#{option.votes.count}"
      end
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reward_helper.rb
module RewardHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_application_footer.html.haml
/ Footer
%footer.bg-slate-800
  .container.flex.flex-col-reverse.justify-between.px-6.py-5.mx-auto.space-y-8.md:flex-row.md:space-y-0
    / Logo and social links container
    .flex.flex-col-reverse.items-center.justify-between.space-y-12.md:flex-col.md:space-y-0.md:items-start
      .mx-auto.my-6.text-center.text-white.md:hidden
        Copright © 2022, All Rights Reserved
      / Logo
      %div
        %img.h-8{:alt => "", :src => ""}/
      -# / Social Links Container
      -# .flex.justify.center.space-x-4
      -#   / Link 1
      -#   %a{:href => "#"}
      -#     %img.h-8{:alt => "", :src => "images/icon-facebook.svg"}/
      -#   / Link 2
      -#   %a{:href => "#"}
      -#     %img.h-8{:alt => "", :src => "images/icon-twitter.svg"}/
      -#   / Link 3
      -#   %a{:href => "#"}
      -#     %img.h-8{:alt => "", :src => "images/icon-youtube.svg"}/
    / List container
    .flex.justify-around.space-x-32
      .flex.flex-col.space-y-3.text-white
        %p.hover.text-gray-100= link_to "Home", root_path
        %p.hover.text-gray-100= link_to "Survey", surveys_path
        %p.hover.text-gray-100= link_to "Enrollments", enrollments_path
      .flex.flex-col.space-y-3.text-white
        %a.hover:text-brightRed{:href => "#"} Privacy Policy
        %a.hover:text-brightRed{:href => "#"} Terms & Conditions
    / Input Container
    .flex-flex-col.justify-between
      %form
        .flex-space-x-3
          %input.flex-1.px-4.rounded-full.focus:outline-none{:placeholder => "Subscribe", :type => "text"}/
          %button.px-6.py-2.text-white.rounded-full.bg-brightGreen.hover:bg-brightGreenLight.focus:outline-none
            Go
      .hidden.text-white.py-6.md:block
        %p= @copyright

app/views/shared/_application_nav.html.haml
/ Nav bar
%nav.bg-slate-800.py-4.px-3
  / Flex container
  .flex.items-center.justify-between
    / Logo
    .pt-2.px-6
      = image_tag("logos/ccname", width: "150px")
    / Menu Items
    .hidden.md:flex.space-x-6
      %p.hover.text-gray-100= link_to "Home", root_path
      %p.hover.text-gray-100= link_to "Surveys", surveys_path
      %p.hover.text-gray-100= link_to "Enrollments", enrollments_path
      %p.hover.text-gray-100= link_to "My Rewards", rewards_path
      %p.hover.text-gray-100= link_to "My Profile", profiles_path
      - if user_signed_in?
        %p.hover.text-gray-100= link_to current_user.email, edit_user_registration_path 
        = login_helper "text-gray-100"
      - admins_only do
        %p.hover.text-gray-100= link_to "Admin", admin_root_path
    / Button
    %a.hidden.p-3.px-6.pt-2.text-white.bg-brightGreen.rounded-full.baseline.hover:bg-brightGreenLight.md:block{:href => "#"} Get Started
    / Hamburger Icon
    %button#menu-btn.block.hamburger.md:hidden.focus:outline-none
      %span.hamburger-top
      %span.hamburger-middle
      %span.hamburger-bottom
  / Mobile Menu
  .md:hidden
    #menu.absolute.flex-col.items-center.self-end.hidden.py-8.mt-10.space-y-6.font-bold.bg-white.sm:w-auto.sm:self-center.left-6.right-6.drop-shadow-md
      %p.hover.text-gray-100= link_to "Home", root_path
      %p.hover.text-gray-100= link_to "Survey", surveys_path
      %p.hover.text-gray-100= link_to "Enrollments", enrollments_path
      %p.hover.text-gray-100= link_to "My Profile", profiles_path
      - if user_signed_in?
        %p.hover.text-gray-100= link_to current_user.email, edit_user_registration_path
        = login_helper "text-gray-100"
      - admins_only do
        %p.hover.text-gray-100= link_to "Admin", admin_root_path
    
-# %nav.bg-slate-800
-#   .mx-auto.max-w-7xl.px-4.sm.px-6.lg.px-8
-#     .flex.h-16.items-center.justify-between
-#       = image_tag("logos/ccname.png", width: "150px")
-#       .flex.items-center
-#         .flex-shrink-0
-#           = link_to "Home", root_path, class:"text-sm p-3 font-medium text-gray-200 transition-colors duration-300 cursor-pointer transform hover:text-blue-400"
-#           = link_to "Surveys", surveys_path, class:"text-sm p-3 font-medium text-gray-200 transition-colors duration-300 cursor-pointer transform hover:text-blue-400"
-#           = link_to "Enrollments", enrollments_path, class:"text-sm p-3 font-medium text-gray-200 transition-colors duration-300 cursor-pointer transform hover:text-blue-400"
-#       .flex-items-center
-#         .flex-shrink-0
-#           = link_to "My Profile", profiles_path, class:"text-sm p-3 font-medium text-gray-200 transition-colors duration-300 cursor-pointer transform hover:text-blue-400"
-#           - if user_signed_in?
-#             = link_to current_user.email, edit_user_registration_path, class:"text-sm p-3 font-medium text-gray-200 transition-colors duration-300 cursor-pointer transform hover:text-blue-400"
-#           = login_helper "text-sm p-3 font-medium text-gray-200 transition-colors duration-300 cursor-pointer transform hover:text-blue-400"
-#           - admins_only do
-#             = link_to "Admin", admin_root_path, class:"text-sm p-3 font-medium text-gray-200 transition-colors duration-300 cursor-pointer transform hover:text-blue-400"

app/views/shared/_nav.html.haml
%div{:class => location}
  = link_to "Home", root_path
  = link_to "Surveys", surveys_path
  - admins_only do
    = link_to "Admin", admin_root_path
  = current_user.class