config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'application#index'
    resources :users
    resources :categories, except: [:show]
    resources :surveys, except: [:show]
    resources :polls, except: [:show]
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :votes, only: [:create]
  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :profiles, path: 'my-profile', except: :show
  resources :rewards, path: 'my-rewards', only: [:index]
  resources :enrollments
  resources :polls do
    resources :completions, only: [:create]     
  end
  patch 'questions/:id/move', controller: 'polls', action: :move
  root "home#index"
  resources :surveys do
    resources :completions, only: [:create]     
    resources :enrollments, only: [:new, :create]
  end
end

app/models/survey.rb
class Survey < ApplicationRecord
	belongs_to :organizer, class_name: "User", foreign_key: "user_id"
	belongs_to :category
	has_many :completions, as: :completion_source
	has_many :enrollments, dependent: :destroy
  has_many :experiences, as: :experience_source
  has_many :rewards_cashes, as: :rewards_cash_source
  has_many :survey_rewards, as: :survey_reward_source	
	validates :survey_name, presence: true, length: {minimum: 5}
	validates :description, :start_date, :end_date, :cpi, :loi, :category, :survey_reward, :rewards_cash, :experience, presence: true

	def enrolled(user)
		self.enrollments.where(user_id: [user.id], survey_id: [self.id].empty?)
	end
end

app/controllers/admin/surveys_controller.rb
class Admin::SurveysController < Admin::ApplicationController
	before_action :set_survey, only: [:show, :edit, :update, :destroy]  
	before_action :authenticate_user!, except: [:index, :show]


	def index
		@surveys = Survey.order(:id)
	end
	
  def create
    @survey = Survey.new(survey_params)

    authorize @survey, :create?
    @survey.organizer = current_user

    respond_to do |format|
      if @survey.save
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

	def edit
		
	end

	def update
		if @survey.update(survey_params)
			flash[:notice] = "Survey has been updated"
			redirect_to survey_url(@survey)
		else
			flash[:alert] = "Survey has not been updated"
			render "edit"
		end
	end

	def destroy
    	@survey.destroy

	    respond_to do |format|
	      format.html { redirect_to admin_surveys_path, notice: "Survey was successfully destroyed." }
	      format.json { head :no_content }
    end

	end

	private

    def survey_params
      params.require(:survey).permit(:survey_name, 
                                    :description, 
                                    :location,
                                    :start_date,
                                    :end_date,
                                    :cpi,
                                    :loi,
                                    :survey_id,
                                    :category_id,
                                    :experience,
                                    :rewards_cash,
                                    :survey_reward
                                    )
    end

	def set_survey
		@survey = Survey.find(params[:id])
	end
end

app/controllers/surveys_controller.rb
  class SurveysController < ApplicationController
  before_action :set_survey, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :verify_admin, only: [ :new ]

  def index
    @surveys = Survey.order(created_at: :desc)
    @categories = Category.order(:name)
    @enrollments = Enrollment.all
    authorize @surveys, :index?
    @polls = Poll.all.where.not(status: ['draft', 'closed'] )
    @admin_polls = Poll.all
  end

  def show
    authorize @survey, :show?
    @completed_survey =  current_user.completions.where(completion_source_type: "Survey").find_by(completion_source_id: @survey.id)      
  end

  def new
    @survey = Survey.new

    authorize @survey, :new?
  end

  def edit
    authorize @survey, :edit?
  end

  def update
    authorize @survey, :update?

    respond_to do |format|
      if @survey.update(survey_params)
        format.html { redirect_to survey_url(@survey), notice: "Survey was successfully updated." }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @survey, :destroy?
    @survey.destroy

    respond_to do |format|
      format.html { redirect_to surveys_url, notice: "Survey was successfully destroyed." }
    end
  end

  private
    def set_survey
      @survey = Survey.find(params[:id])

      rescue ActiveRecord::RecordNotFound
      flash.alert = "The page you requested does not exist"
      redirect_to surveys_path

    end

    def verify_admin
      unless current_user.admin?
        redirect_to surveys_path
      end
    end

    def survey_params
      params.require(:survey).permit(:survey_name, 
                                    :description, 
                                    :location,
                                    :start_date,
                                    :end_date,
                                    :cpi,
                                    :loi,
                                    :survey_id,
                                    :category_id,
                                    :experience,
                                    :rewards_cash,
                                    :survey_reward
                                    )
    end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.haml
.mt-8.sm:mx-auto.sm:w-full.sm:max-w-md
  .bg-white.py-8.px-4.shadow.sm:rounded-lg.sm:px-10
    = simple_form_for([:admin, @survey]) do |f|
      = f.error_notification
      = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?
      .my-2
        = f.input :survey_name, required: true, class: 'block text-sm font-medium text-gray-700'
        .mt-1
        = f.input :description, required: true, class: "appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm placeholder-gray-400 focus:outline-none focus:ring-blue-500 focus:border-blue-500 sm:text-sm" 
      .my-2
        = f.input :start_date, required: true, class: 'block text-sm font-medium text-gray-700'
      .my-2
        = f.input :end_date, required: true, class: 'block text-sm font-medium text-gray-700'
      .my-2
        = f.input :category_id, required: true, collection: Category.all, label: "Select Category", prompt: true, class: 'block text-sm font-medium text-gray-700'
      .my-2
        = f.input :cpi, input_html: { min: '0', step: 'any'}, required: true, class: 'block text-sm font-medium text-gray-700'
        = f.input :loi, input_html: { min: '0', step: 'any'}, required: true, class: 'block text-sm font-medium text-gray-700'
        = f.input :experience, required: true, class: 'block text-sm font-medium text-gray-700'
        = f.input :rewards_cash, required: true, label: 'CloutCash', class: 'block text-sm font-medium text-gray-700'
      .my-2
        = f.input :survey_reward, required: true, class: 'block text-sm font-medium text-gray-700'

      %p Location
      = f.country_select :location

      %button.w-full.flex.justify-center.mt-4.py-2.px-4.border.border-transparent.rounded-md.shadow-sm.text-sm.font-medium.text-white.bg-blue-600.hover:bg-blue-700.focus:outline-none.focus:ring-2.focus:ring-offset-2.focus:ring-blue-500{:type => "submit"}
        = f.button :submit

app/views/surveys/_survey.html.haml
=link_to survey_path(survey) do
  .flex.flex-col.relative.block.rounded-sm.border-t-4.border-slate-200.p-8.pb-24.shadow-xl.md:flex-row
    .h5.text-4xl.text-brightGreen.font-bold= "#{number_to_currency(survey.cpi)}"
    .absolute.right-4.top-4= image_tag("low-poly-grid", width: "100px")
    .absolute.left-8.bottom-2.text-md.font-semibold.text-gray-700.mr2.mb-2= "Duration: #{survey.loi} minutes"
    .absolute.right-4.bottom-4.rounded-full.bg-slate-500.px-3.py-1.5.text-xs.text-white.font-medium= survey.category.name



-# .p-6.m-4.max-w-md.mx-auto.bg-white.rounded-xl.shadow-xl.flex.items-center.space-x-10
-#   .shrink-0
-#     %img.h-24.w-25{:alt => "Category", :src => "https://picsum.photos/100"}/
-#     .py-3.px-4.text-gray-600.text-md.text-center= " #{time_ago_in_words(survey.created_at)} ago"
-#   %div
-#     .px-2.pt-1.pb-2
-#     %p.text-2xl.font-bold= survey.survey_name
-#     %p.text-sm.text-indigo-600.font-bold.mb-4.mt-0= link_to survey.category.name
-#     .pt-0.pb-0
-#     %p.inline-block.bg-gray-200.rounded-full.px-3.py-1.text-md.font-semibold.text-gray-700.mr-2.mb-2.cursor-default= "Reward: #{number_to_currency(survey.cpi)}"
-#     %p.inline-block.bg-gray-200.rounded-full.px-3.py-1.text-md.font-semibold.text-gray-700.mr-2.mb-2.cursor-default= "Duration: #{survey.loi}m"
-#     .px-6.pt-4.pb-2
-#     %button{:class => "bg-gradient-to-r from-blue-400 to-slate-500 hover:from-slate-700 hover:to-blue-700 text-white font-bold py-2 px-4 rounded-full"}= link_to 'Show Survey', survey_path(survey)

app/views/surveys/edit.html.haml
%h1.text-2xl.font-bold.py-6.text-center Editing survey
= render "form", survey: @survey
%br/
%div
  = link_to "Show this survey", @survey
  |
  \#{link_to "Back to surveys", surveys_path}

app/views/surveys/index.html.haml
%p{:style => "color: green ", class: "text-center"}= notice
%h1.text-3xl.font-bold.mb-4.mt-5.text-center Surveys
.container.flex.flex-col.px-4.mx-auto.mt-10.space-y-12.md:flex-row
.p-10.grid.grid-cols-1.sm.grid-cols-1.md.grid-cols-4.lg.grid-cols-4.xl.grid-cols-4.gap-5
  - @surveys.each do |survey|
    = render survey

  - if current_user.admin?
    - @admin_polls.each do |poll| 
      =link_to poll_path(poll) do 
        .flex.flex-col.relative.rounded-sm.border-t-4.border-slate-200.p-6.pb-20.shadow-xl
          .h1.text-lg.text-black.font-bold.text-gray-600 Poll
          .h5.text-4xl.text-green-800.font-bold= "#{number_to_currency(poll.rewards_cash)}"
          -# .h1.text-3xl.text-black.font-bold= poll.topic
          .absolute.left-8.bottom-2.text-md.font-semibold.text-gray-700.mb-6 Click to participate
  - else 
    - @polls.each do |poll| 
      =link_to poll_path(poll) do 
        .flex.flex-col.relative.rounded-sm.border-t-4.border-slate-200.p-6.pb-20.shadow-xl
          .h1.text-lg.text-black.font-bold.text-gray-600 Poll
          .h5.text-4xl.text-green-800.font-bold= "#{number_to_currency(poll.rewards_cash)}"
          -# .h1.text-3xl.text-black.font-bold= poll.topic
          .absolute.left-8.bottom-2.text-md.font-semibold.text-gray-700.mb-6 Click to participate
.text-center
  = link_to "New survey", new_survey_path if current_user.admin
  = link_to "New Poll", new_poll_path if current_user.admin

app/views/surveys/new.html.haml
%h1.text-center New survey
= render "form", survey: @survey
%br/
.text-center
  = link_to "Back to surveys", surveys_path

app/views/surveys/show.html.haml
%p{:style => "color: green ", class: "text-center"}= notice
.relative.mx-auto.bg-gray
  .absolute.inset-0
    .bg-white{:class => "h-1/3 sm:h-2/3"}
  .relative.mx-auto.max-w-7xl
    .mx-auto.mt-12.grid.max-w-lg.gap-5
      .flex.flex-col.overflow-hidden.rounded-lg.shadow-lg
        .flex-shrink-0
          %img.h-50.w-full.object-cover{:alt => "", :src => "https://picsum.photos/100"}/
        .flex.flex-1.flex-col.justify-between.bg-white.p-6
          .flex-1
            %p.text-sm.font-medium.text-indigo-600
              %p.text-2xl.font-semibold.text-gray-900.text-center= @survey.survey_name
              %p.text-indigo-600.font-bold.text-sm.mb-4.mt-0.text-center= @survey.category.name
              %p.py-1.text-md.font-semibold.text-gray-700= "Survey Reward: #{number_to_currency(@survey.survey_reward)}"
              %p.py-1.text-md.font-semibold.text-gray-700= "CloutCash: #{number_to_currency(@survey.rewards_cash)}"
              %p.py-1.text-md.font-semibold.text-gray-700= "CloutXP: #{@survey.experience}xp"
              %p.py-1.text-md.font-semibold.text-gray-700= "Estimated Duration: #{@survey.loi} minutes"
              %p.text-gray-700.font-bold.text-md.mb-4.mt-0= "Description: #{@survey.description}"
              %p.text-gray-700.font-bold.text-md.mb-4.mt-0= "Start Date: #{(@survey.start_date).strftime "%d-%m-%Y"}"
              %p.text-gray-700.font-bold.text-md.mb-4.mt-0= "End Date: #{(@survey.end_date).strftime "%d-%m-%Y"}"
              %p.text-gray-700.font-bold.text-md.mb-4.mt-0= "Location: #{@survey.location}"
              .px-6.pt-4.pb-2.text-center
                = button_to 'Start Survey', survey_completions_path(@survey), method: :post, class: "bg-gradient-to-r from-blue-500 to-green-400 hover:from-green-700 hover:to-blue-700 text-white font-bold py-2 px-4 rounded-full" unless @completed_survey
              %div.p-2.text-center
                .text-gray-600.text-lg.border-t.py-3= " #{time_ago_in_words(@survey.created_at)} ago"

.text-center
  = link_to "Edit this survey", edit_survey_path(@survey) if current_user.admin
  
  = link_to "Back to surveys", surveys_path
  |
  = link_to "Enroll Survey", new_survey_enrollment_path(@survey), method: :post, class: "new"
  = button_to "Destroy this survey", @survey, method: :delete if current_user.admin