config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    root 'application#index'
    resources :users
    resources :categories, except: [:show]
    resources :surveys, except: [:show]
    resources :polls, except: [:show]
  end

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register'}

  resources :votes, only: [:create]
  resources :users, only: [:show]
  resources :categories, only: [:show]
  resources :profiles, path: 'my-profile', except: :show
  resources :rewards, path: 'my-rewards', only: [:index]
  resources :enrollments
  resources :polls do
    resources :completions, only: [:create]     
  end
  patch 'questions/:id/move', controller: 'polls', action: :move
  root "home#index"
  resources :surveys do
    resources :completions, only: [:create]     
    resources :enrollments, only: [:new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
	validates :name, presence: true, length: {minimum: 5 }
	validates_uniqueness_of :name

	has_many :surveys, dependent: :destroy
end

app/models/completion.rb
class Completion < ApplicationRecord
  belongs_to :user
  belongs_to :completion_source, polymorphic: true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord

  enum :status, { inactive: 0, in_process: 10, completed_full: 20, completed_disqualified: 30, terminated: 40 }

  belongs_to :survey
  belongs_to :user

  validates :user, :survey, presence: true

  validates_uniqueness_of :user_id, scope: :survey_id #user can't be enrolled in a survey more than once
  validates_uniqueness_of :survey_id, scope: :user_id #user can't be enrolled in a survey more than once

  def to_s
    user.to_s + survey.to_s
  end


end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  belongs_to :experience_source, polymorphic: true
end

app/models/guest_user.rb
class GuestUser < User
	attr_accessor :name, :first_name, :last_name, :email
end

app/models/poll.rb
class Poll < ApplicationRecord
  has_many :questions, dependent: :delete_all
  has_many :experiences, as: :experience_source
  has_many :rewards_cashes, as: :rewards_cash_source

  accepts_nested_attributes_for :questions, :reject_if => :all_blank, :allow_destroy => true

  enum status: { draft: 'draft', open: 'open', closed: 'closed' }

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user

  validates :age, :gender, :ethnicity, :country, presence: true

  def self.select_options_for_gender
    [['Male', 'male'], ['Female','female'], ['Other','other']]
  end
  def self.select_options_for_ethnicity
    [['American Indian', 'american indian'], ['Asian','asian'], ['Black or African American','black or african american'], ['Hispanic or Latino ', 'hispanic or latino'], ['Native Hawaiian','native hawaiian'], ['White or Caucasian','white or caucasian']]
  end
end

app/models/question.rb
class Question < ApplicationRecord
  acts_as_list
  
  has_many :vote_options, dependent: :delete_all
  belongs_to :poll 
  accepts_nested_attributes_for :vote_options, :reject_if => :all_blank, :allow_destroy => true


  def self.select_options_for_type
    [['Single Select', 'single_select'], ['Multi Select','multi_select']]
  end

  def normalized_votes_for(option)
    votes_summary == 0 ? 0 : (option.votes.count.to_f / votes_summary) * 100
  end

  def votes_summary
    vote_options.inject(0) {|summary, option| summary + option.votes.count}
  end

end

app/models/rewards_cash.rb
class RewardsCash < ApplicationRecord
  belongs_to :rewards_cash_source, polymorphic: true
  belongs_to :user
end

app/models/survey.rb
class Survey < ApplicationRecord
	belongs_to :organizer, class_name: "User", foreign_key: "user_id"
	belongs_to :category
	has_many :completions, as: :completion_source
	has_many :enrollments, dependent: :destroy
  has_many :experiences, as: :experience_source
  has_many :rewards_cashes, as: :rewards_cash_source
  has_many :survey_rewards, as: :survey_reward_source	
	validates :survey_name, presence: true, length: {minimum: 5}
	validates :description, :start_date, :end_date, :cpi, :loi, :category, :survey_reward, :rewards_cash, :experience, presence: true

	def enrolled(user)
		self.enrollments.where(user_id: [user.id], survey_id: [self.id].empty?)
	end
end

app/models/survey_reward.rb
class SurveyReward < ApplicationRecord
  belongs_to :survey_reward_source, polymorphic: true
  belongs_to :user 
end

app/models/user.rb
class User < ApplicationRecord
  has_many :organized_surveys, class_name: "Survey", dependent: :destroy
  has_many :completions, dependent: :destroy
  has_many :completed_surveys, through: :completions
  has_many :enrollments
  has_many :rewards_cashes, dependent: :destroy
  has_many :experiences, dependent: :destroy
  has_many :survey_rewards, dependent: :destroy
  has_one :profile, dependent: :destroy
  validates :first_name, :last_name, :email, presence: true
  has_many :votes, dependent: :destroy
  has_many :vote_options, through: :votes
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def to_s
  "#{username}"
  end
  
  def voted_for?(question)
    Rails.cache.fetch('user_' + id.to_s + '_voted_for_' + question.id.to_s) { vote_options.any? {|v| v.question == question } }
  end

  def full_name
  "#{first_name} #{last_name}"           
  end

  def enroll_survey(survey)
    self.enrollments.create(survey: survey)
  end

  def total_rewards_cash
  rewards_cashes.sum(:rewards_cash_amount)
  end

  def total_experience
  experiences.sum(:experience_amount)
  end

  def total_survey_reward
  survey_rewards.sum(:survey_reward_amount)
  end

end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :user
  validates :vote_options, presence: true
  has_and_belongs_to_many :vote_options
end

app/models/vote_option.rb
class VoteOption < ApplicationRecord
  belongs_to :question
  has_and_belongs_to_many :votes
  has_many :users, through: :votes
  validates :title, presence: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::ApplicationController
	before_action :set_category, only: [:edit, :update, :destroy]  
	before_action :authenticate_user!, except: [:index, :show]


	def index
		@categories = Category.order(:id)
	end

	def new
		@category = Category.new
	end

	def create
		@category = Category.new(category_params)

		if @category.save
			flash[:notice] = "Category has been created"
			redirect_to admin_categories_path
		else
			flash.now[:alert] = "Category has not been created"
			render "new"
		end
	end

	def edit
		
	end

	def update
		if @category.update(category_params)
			flash[:notice] = "Category has been updated"
			redirect_to admin_categories_path
		else
			flash[:alert] = "Category has not been updated"
			render "edit"
		end
	end

	def destroy
    	@category.destroy

	    respond_to do |format|
	      format.html { redirect_to admin_categories_path, notice: "Category was successfully destroyed." }
	      format.json { head :no_content }
    end

	end

	private

	def category_params
		params.require(:category).permit(:name, :summary)
	end

	def set_category
		@category = Category.find(params[:id])
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
	before_action :set_category, only: [:show]
	skip_after_action :verify_authorized

	def show
		@categories = Category.order(:name)
		@category_surveys = @category.surveys.order(created_at: :desc)

	end

	private

	def set_category
		@category = Category.find(params[:id])

	rescue ActiveRecord::RecordNotFound
		flash[:alert] = "The category you were looking for could not be found"
		redirect_to(request.referrer || surveys_url)
	end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/polls_helper.rb
module PollsHelper
  def visualize_votes_for(option)
    content_tag :div, class: 'w-full bg-gray-200 rounded-full h-2.5 dark:bg-gray-700' do
      content_tag :div, class: 'bg-blue-600 h-2.5 rounded-full',
                  style: "width: #{option.question.normalized_votes_for(option)}%" do
        "#{option.votes.count}"
      end
    end
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reward_helper.rb
module RewardHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/show.html.haml
%body
%ul.actions
  - admins_only do
    %p{:class => "inline-flex items-center justify-center rounded-md border border-transparent bg-indigo-600 px-4 py-2 text-sm font-medium text-white shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 sm:w-auto", :type => "button"}= link_to "Go to Dashboard", admin_root_path if current_user.admin
.row
.col-sm-6.text-center
  %h4 Discover your surveys
  = form_tag surveys_path, class: "form-horizontal", method: :get do
    .form.group.form-group.lg
      .col-sm-10
        = text_field_tag :query, params[:query], placeholder: "Search surveys here", autofocus: :true, class: "form-control"
      %div{:class => "class=", "col-sm-2" => ""}
        = submit_tag "Find", class: "btn btn-default btn-lg"
        - if params[:query].present?
          = link_to "Clear", surveys_path
.col-sm-6.text-center
  .sidebar
    %h3.discover Discover
    %ul.nav.nav-pills.nav-stacked
      %li{:class => "#{"active" if current_page?("/surveys")}"}= link_to "All Surveys", surveys_path
      - @categories.each do |category|
        %li=link_to category.name, category_path(category)
      %h1.text-2xl.text-center.text-indigo-500.font-bold= "#{@category.name} Surveys"
      = link_to "Edit", edit_admin_category_path(@category), class: "text-indigo-500 underline", :type => "button" if current_user.admin
.p-10.grid.grid-cols-1.sm.grid-cols-1.md.grid-cols-3.lg.grid-cols-3.xl.grid-cols-3.gap-5
  - @category_surveys.each do |survey|
    = render survey
  -# .p-6.m-4.max-w-lg.mx-auto.bg-white.rounded-xl.shadow-xl.flex.items-center.space-x-10
  -#   .shrink-0
  -#     %img.w-full{:alt => "Category", :src => "https://picsum.photos/100"}/
  -#     .py-3.px-6.text-gray-600.text-lg= " #{time_ago_in_words(survey.created_at)} ago"
  -#   %div
  -#     .px-2.pt-1.pb-2
  -#     %p.text-2xl.font-bold= survey.survey_name
  -#     %p.text-sm.text-indigo-600.font-bold.mb-4.mt-0= "Location: #{survey.location}"
  -#     .pt-0.pb-0
  -#     %p.inline-block.rounded-full.px-3.py-1.text-md.font-semibold.text-gray-700.mr-2.mb-2.cursor-default= "Start Date: #{time_format(survey.start_date)}"
  -#     %p.inline-block.rounded-full.px-3.py-1.text-md.font-semibold.text-gray-700.mr-2.mb-2.cursor-default= "Organized by: #{survey.organizer.full_name}"
  -#     .px-6.pt-4.pb-2
  -#     %button{:class => "bg-gradient-to-r from-green-400 to-blue-500 hover:from-blue-700 hover:to-green-700 text-white font-bold py-2 px-4 rounded-full"}= link_to 'Show Survey', survey_path(survey)